// Comprehensive list of sectors for startups and investors
export const ALL_SECTORS = [
  'FinTech',
  'HealthTech',
  'EdTech',
  'E-commerce',
  'SaaS',
  'AI/ML',
  'Blockchain',
  'Cybersecurity',
  'Real Estate Tech',
  'FoodTech',
  'AgriTech',
  'CleanTech',
  'Energy',
  'Transportation',
  'TravelTech',
  'Entertainment',
  'Gaming',
  'Social Media',
  'Marketplace',
  'HR Tech',
  'LegalTech',
  'PropTech',
  'InsurTech',
  'RetailTech',
  'FashionTech',
  'BeautyTech',
  'FitnessTech',
  'MedTech',
  'BioTech',
  'SpaceTech',
  'Robotics',
  'IoT',
  'AR/VR',
  'Web3',
  'Crypto',
  'DeFi',
  'NFT',
  'Telecom',
  'Media',
  'Publishing',
  'Music',
  'Sports',
  'PetTech',
  'SeniorTech',
  'FemTech',
  'Other',
];

// Sectors for filtering (includes 'All' option)
export const FILTER_SECTORS = ['All', ...ALL_SECTORS];

